version: '3'

services:
  csg_hack:
    build: .
    container_name: csg_hack
    volumes:
      - ./run.sh:/team_2_1/run.sh
      - ./src:/team_2_1/src
      - ./bin:/team_2_1/bin
      - ./output:/team_2_1/output
    command: /bin/bash
    tty: true
    stdin_open: true